### ISSUE TITLE
GA function optimisation func(int x, int y) sample

### ISSUE THREAD

**Issue by fish55** [giacomelli/GeneticSharp#1]
Hi i wanted to ask you about sample
Howto solve this task using GeneticSharp. Can you provide code sample please?
Where X have Range (0....7) Y have Range (0 ....100) Step 5 (for calclulatiion for brute force)
***************************************************************
So problem i dont know how many cromosomes should i use? In my mind there are idea
In each chromosome should be only 2 genes GeneX have range (0 ..7) and GeneY(0..100)
How i can implement this with GeneticSharp? Which method should be for GeneratePopulationm, CrossOver,Mutation?
public void FillPopulation(){
var population = new Population(50);
Random randpar1 = new Random();
            randpar1.Next(1, 20);
            //create the chromosomes
            for (var p = 0; p < 50; p++)
            {
                var chromosome = new Chromosome();
                for (var g = 0; g < 2; g++)
                {
                    chromosome.Genes.Add(new Gene(randpar1.Next(-100, 200)));
                }
                //chromosome.Genes.Shuffle();
                population.Solutions.Add(chromosome);
            }
}

**********************************************************
public static double CalculateFitness(Chromosome chromosome)
        { 
            double n = 9;
            var x = chromosome.Genes[0].RealValue;
            var y = chromosome.Genes[1].RealValue;
            double f1 = System.Math.Pow(15 * x * y * (1 - x) * (1 - y) *
                System.Math.Sin(n * System.Math.PI * x) * System.Math.Sin(n * System.Math.PI * y), 2);
       
            return f1;
        }

**Comment by giacomelli** [comment]
I've push a sample project based on your question: https://github.com/giacomelli/GeneticSharp/tree/master/src/Samples/Issue1Sample

Hope it can help you to find your solution.

**Comment by rrduarte** [comment]
There is a bug on this sample (i didnt check if it is a project bug). 

BestChromosome properties are changing during the iterations. 
If you get X and Y values on the end of the program, they dont generate the same Fitness.

But, if you use the method GetGenes (base object), then you can get the right values of X and Y.

**Comment by giacomelli** [comment]
I recently wrote a tutorial about function optimization with GeneticSharp that use binary chromosomes to solve a similar problem: http://diegogiacomelli.com.br/function-optimization-with-geneticsharp/
