### ISSUE TITLE
Group fitness

### ISSUE THREAD

**Issue by acroca** [giacomelli/GeneticSharp#11]
Hi, I'd like to implement a type of Tournament selection where I can run the fitness of them together in the same simulation. I'm doing an AI for a game and I'd like to run a group of AIs at the same time and select the one that ends up performing better. In my game AIs can't run alone, that's why I need them to run in group. Basically their performance depends a bit on the other ones as well.
Is there any easy way to do so? I feel I'll have to implement my own `GeneticAlgorithm` because everything is quite hardcoded to check the fitness individually.

**Comment by giacomelli** [comment]
If I understood what you want to achieve, you can run all fitness async, like I did in this experiment: https://github.com/giacomelli/SurvivorAI/ (take a look on BridgeChallengeScene).
or you can run your whole simulation, store the data you need to your fitness evaluation and then run the GA.

**Comment by acroca** [comment]
I see. I'll have a look at the SurvivorAI and reopen this issue if I have any more questions.

But in other words, I wanted something like evaluate fitness in groups, like in a tournament. So the fitness of each chromosome will depend on their group. So I'd need to run a game simulation with a bunch of chromosomes, start the game using each of them as a different AI, run the game for a bit and see who's the winner...

**Comment by giacomelli** [comment]
Well, I think you can get this passing your IPopulation as a constructor argument of your IFitness implementation, in this way you will be able to evaluate each chromosome fitness and use information of others chromosomes through population.CurrentGeneration.Chromosomes.
