### ISSUE TITLE
GeneticAlgorithm.Resume() not working

### ISSUE THREAD

**Issue by fulviofarina** [giacomelli/GeneticSharp#12]
Hi, I try to resume the genetic algorithm but after it is stopped it is not running again.
Any idea?

P.S.: your program rocks by the way. I'm doing the knapsack problem

**Comment by giacomelli** [comment]
Hi! 

Did you receive any exeception when you try to resume the GA?

If your GA already reach the termination criteria and you try to resume it, you will see an exception. In this case you can set a new termination and resume it again.

**Comment by fulviofarina** [comment]
Thanks for your answer. No exception, but I realized the problem was a cross-thread access to an object.
It's working fine now. I love this library.
