### ISSUE TITLE
NuGet Package Installation for Unity Project Failure

### ISSUE THREAD

**Issue by Ahmed-YehiaGPEL** [giacomelli/GeneticSharp#14]
Hello,

While trying to install the NuGet package inside a Unity3D project version 5.6.0f3 the package installation fails because of NuGet trying to install another package **HelperSharp** which is not compatible with Unity3D .NET Profile.

Screen shot below for more clarification.

![image](https://cloud.githubusercontent.com/assets/10068638/26631170/222b1668-460a-11e7-9f17-927941035ebe.png)

What steps should I take ? Possibly removing dependencies of both packages so that the GeneticSharp package can be installed alone.

**Comment by giacomelli** [comment]
Remove HelperSharp can be an option, because there are few methods from it been used by GeneticSharp.

**Comment by hendrik-schulte** [comment]
Installing GeneticSharp with NuGet didn't work for me neither.
However, importing the dlls did the job (including HelperSharp)! I'm also on Unity 5.6.0f3.

**Comment by Ahmed-YehiaGPEL** [comment]
Good to know that it works when importing the DLLs inside Unity I'll go with that for now, I've cloned and built the projects to get what's needed.

I might remove the dependencies and change what's used by Helper Sharp within the package, if I did so I'll be sure to open a request here to integrate if possible.

Thank you all for your response
