### ISSUE TITLE
Compilation tutorial

### ISSUE THREAD

**Issue by qrzychu** [giacomelli/GeneticSharp#21]
Hi, I will use your awesome project for my masters thesis.

I will need to add few things, like mutation that firstly gets random number and determines which child mutation to use later.

Usage:
`new RandomizedMutation({
{new UniformMutation(), 0.2}, // this are chances for that mutation
{new AnotherMutation(), 0.8}, // this are chances for that mutation
});`

So I created fork, cloned repo, opened VS2017 aaaaand... Nothing. I can't get to compile. Are there some magick steps in order to do that?

I really wanted to be involved in OpenSource project for the first time.

**Comment by giacomelli** [comment]
Hi! I'm glad to know that you will use GeneticSharp in your master thesis.

BTW, your RandomizedMutation is a good option of mutation, please, when you finish it, make a pull-reques to GeneticSharp.

About open it on VS2017, what errors are you getting on VS?

**Comment by qrzychu** [comment]
Well, this time it just worked :D
I have no idea why, maybe last time I tried my VS was crushed in some way, because when I opened it Resharper analysis showed 289 errors, which went down to zero without me doing anything. 
Still, this Gtk runner app has missing references to gtk stuff, I have unloaded this project.

Thanks for quick response, I will try my best to add something good :)

**Comment by giacomelli** [comment]
Nice!

Just install GtkSharp in order to run the gtk runner app.

If you use Chocolatey, run the command below:

`choco install gtksharp`
