### ISSUE TITLE
Any plan to migrate code to .Net Standard?

### ISSUE THREAD

**Issue by Guymestef** [giacomelli/GeneticSharp#24]
Hello,

Have you start looking for .Net Standard, or it isn't planned at all?

**Comment by giacomelli** [comment]
Yeah, GeneticSharp will support it. 
Right now I cannot say when this migration will take place, but it will happen!

**Comment by jameschch** [comment]
Would also appreciate a Core compatible package at some point. The dependency that breaks .net standard can be brought into line with a workaround: 

https://github.com/amibar/SmartThreadPool/pull/17
