### ISSUE TITLE
Pull Request failed

### ISSUE THREAD

**Issue by AntonyCorbett** [giacomelli/GeneticSharp#28]
My pull request failed because AppVeyor was attempting to download a resource from codeplex that was not found.

**Comment by giacomelli** [comment]
@AntonyCorbett I add a code review comment on your #27 pull-request.

**Comment by AntonyCorbett** [comment]
@giacomelli thank you. Are you sure you submitted the review? I don't see any review comments attached to the PR.

**Comment by giacomelli** [comment]
@AntonyCorbett sorry, I forgot to submit it, now is there.

**Comment by AntonyCorbett** [comment]
@giacomelli thank you - I will make the required change and resubmit.

**Comment by giacomelli** [comment]
Closed by #27
