### ISSUE TITLE
Add constructor with values to FloatingPointChromosome 

### ISSUE THREAD

**Issue by mersadk** [giacomelli/GeneticSharp#33]
As it is now when ever you create instance of FloatingPointChromosome, it will randomly create gene values.

I have a case where I need to stop optimization at some time, save results to DB and resume it later. For this I need to be able to give gene values to FloatingPointChromosome.

If you are willing to merge, I'll create pull request with this fix.

**Comment by giacomelli** [comment]
This will be a good improvement to FloatingPointChromosome.
Yeah, you could create the pull request.

Thanks.

**Comment by mersadk** [comment]
Done.
