### ISSUE TITLE
How is the number of totalBits, required, computed?

### ISSUE THREAD

**Issue by MattWolf74** [giacomelli/GeneticSharp#42]
Using GeneticSharp, I started working on some optimizations in order to lower the computational power, required. For that purpose I try to lower the totalBits but it does not seem apparent how the required number bits is computed given

- precision
-  of input variable and possible variable range.

Can someone please comment on how the total number bits, required, are computed. Ideally I want to set the totalBits parameter as function of chosen precision and value range.

Thanks

**Comment by giacomelli** [comment]
The four arguments of FloatingPointChromosome's constructor are:

1) The minimum values of numbers inside the chromosome. 
2) The maximum values of numbers inside the chromosome. 
3) The total bits used to represent each number. For example, if your maximum value isis 998, so 10 bits is what you need.

> GeneticSharp will warn you if you try to use a total bits that cannot hold a number inside your floating point chromosome.

4) The number of fraction (scale or decimal) part of the number.

**Comment by MattWolf74** [comment]
What does it mean "if the maximum value is 998"? Do those values refer to
the possible values of input variables or the result of the objective
function? How are the required bits calculated for a floating point number?
I am asking because there are different approaches.

Thanks

**Comment by MattWolf74** [comment]
So it is the input variables to the objective function and hence the number
of bits required is also a function of the fractionDigits specified in each
Chromosome, correct?

**Comment by giacomelli** [comment]
Correct.
