### ISSUE TITLE
Invalid link to PartiallyMappedCrossover's description

### ISSUE THREAD

**Issue by InRedikaWB** [giacomelli/GeneticSharp#50]
**Describe the bug**
Link to PartiallyMappedCrossover's description throw 404.

**To Reproduce**
Open class PartiallyMappedCrossover
Check link in <see> tag [(this)](http://lev4projdissertation.googlecode.com/svn-history/r100/trunk/reading/read/aiRev99.pdf)

Link to line in code: https://github.com/giacomelli/GeneticSharp/blob/master/src/GeneticSharp.Domain/Crossovers/PartiallyMappedCrossover.cs#L16

**Comment by giacomelli** [comment]
Fix by 9825fd002d028d892846f2a0ef033086ad445c9b.
