### ISSUE TITLE
RouletteWheelSelection.SelectFromWheel throws NullReferenceException when first generation is "invalid"

### ISSUE THREAD

**Issue by codingdna2** [giacomelli/GeneticSharp#57]
**To Reproduce**
RouletteWheelSelection.SelectFromWheel throws NullReferenceException when first generation is "invalid" (all chromosome have zero fitness).

**Expected behavior**
A better exception should be thrown. NullReferenceException is confusing and require to debug GeneticSharp.

**Version:**
2.2.0

**Fix Proposal (probably naive)**

Let me know if you like it and if you want me to make a PR.

```
protected static IList<IChromosome> SelectFromWheel(int number, IList<IChromosome> chromosomes, IList<double> rouletteWheel, Func<double> getPointer)
{
    var selected = new List<IChromosome>();

    for (int i = 0; i < number; i++)
    {
        var pointer = getPointer();

        var chromosomeIndex = rouletteWheel.Select((value, index) => new { Value = value, Index = index }).FirstOrDefault(r => r.Value >= pointer)?.Index;
        if (chromosomeIndex == null)
            throw new SelectionException("Generation doesn't contains any chromosome with fitness greater than 0");

        selected.Add(chromosomes[chromosomeIndex.Value]);
    }

    return selected;
}
```

**Comment by giacomelli** [comment]
Yeah, please make the PR, but just a unit test method to validate this case.

**Comment by codingdna2** [comment]
It's not clear the last hint you gave me. In order to include it in `ValidateGenes`, I shall include something like:

            if (chromosomes.All(c => c.Fitness == 0))
            {
                throw new InvalidOperationException("Generation doesn't contains any chromosome with fitness greater than 0");
            }

But I'm not sure this kind of check in ValidateGenes can have side effects..
Is this what you meant?

**Comment by giacomelli** [comment]
Yeah, you're right the ChromosomeExtensions' methods validate other things, but I'm no sure about validate `c.Fitness == 0`, because some kind o problems can have Fitness zero (in some cases negative fitness, so zero is the best one).

Could you please write a unit test that exposes this problem, then I'll have a better understand and solution suggestion for it.
