### ISSUE TITLE
Runtime exception on .NET 4.6.2

### ISSUE THREAD

**Issue by jbrant** [giacomelli/GeneticSharp#58]
I'm running Visual Studio 2013 targeting .NET 4.6.2 with GeneticSharp 2.4.0, and get the following runtime exception when attempting to instantiate a GeneticAlgorithm instance (specifically, when the task executor is set):

`Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.`

Is .NET Framework 4.6.2 still supported, or is .NET standard 2.0.0+ now required?

**Comment by giacomelli** [comment]
If you are just using GeneticSharp from Nuget, you can use it on VS 2013, but if you are building the GeneticSharp's source code from scratch, then you need to follow our guide: [Building the whole solution](https://github.com/giacomelli/GeneticSharp/wiki/setup#building-the-whole-solution).

What is your case?

**Comment by jbrant** [comment]
I'm installing via Nuget (i.e. not building from the source code).

**Comment by giacomelli** [comment]
The Nuget package (https://www.nuget.org/packages/GeneticSharp/) seem to have the right dependencies.

Could you please send, a minimum project sample with this problem happening?

I don't have VS 2013 here, but maybe I can spot what is happening.

**Comment by giacomelli** [comment]
I've created a console project targeting 4.6.2 and I could not reproduce the error.

Can you try the project attached and compare it with your project?
[TestGeneticSharpNet462.zip](https://github.com/giacomelli/GeneticSharp/files/2804389/TestGeneticSharpNet462.zip)

**Comment by jbrant** [comment]
Thank you very much for the exemplar project. I actually did still get the above-referenced error, but at compile time. Interestingly, if I commented out the TaskExecutor override in the GeneticAlgorithm object initializer block (i.e. TaskExecutor = new ParallelTaskExecutor()), this resolved the compilation error. but the same runtime exception was still thrown.

Specifically, this is the compilation error:

`error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

**Comment by jbrant** [comment]
Quick update on this: the infrastructure framework DLLs (i.e. GeneticSharp.Infrastructure.Framework.dll) for both the netstandard2.0 and net462 targets have the same hash. Perhaps Nuget has the .NET standard build for both build targets. This isn't the case for the domain DLL (GeneticSharp.Domain.dll), which would explain why the above-referenced error only occurs when interface with properties or methods from the infrastructure project.

**Comment by giacomelli** [comment]
Yes, you'are right. I opened the assemblies from `geneticsharp.2.4.0.nupkg\lib\net462` in ILSpy:

## GeneticSharp.Domain.dll
![image](https://user-images.githubusercontent.com/177389/51973103-0faf7f80-2464-11e9-9e3f-9b4dfe8bf6d3.png)

## GeneticSharp.Infrastructure.Framework.dll
![image](https://user-images.githubusercontent.com/177389/51973170-2ce44e00-2464-11e9-9925-a4e3b40b46b1.png)

GeneticSharp.Infrastructure.Framework.dll from net462 folder is using .NETStandard instead of .NET Framework.

I'll investigate what is wrong with project files or with the nuget generation.
