### ISSUE TITLE
is it nuget being updated?

### ISSUE THREAD

**Issue by rrduarte** [giacomelli/GeneticSharp#6]
is it nuget being updated?

**Comment by giacomelli** [comment]
Yes. The NuGet package will be updated when adding new feature or fix a bug

**Comment by rrduarte** [comment]
The commits from "Nov 17, 2015" (https://github.com/giacomelli/GeneticSharp/commit/47249354adc7788c1640a8f0f4bc4f8949173b9e) should not trigger a new NuGet package?

**Comment by giacomelli** [comment]
Package version 1.0.94 published.
