### ISSUE TITLE
AlternatingPositionCrossover throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by dxball** [giacomelli/GeneticSharp#61]
**Describe the bug**
Using the `AlternatingPositionCrossover` cause `System.IndexOutOfRangeException`

**To Reproduce**
I've made a sample project, please give a look
[GeneticSharpTest.zip](https://github.com/giacomelli/GeneticSharp/files/3280657/GeneticSharpTest.zip)

**Expected behavior**
Should not throw an exception

**Version:**
2.5.1

**Comment by giacomelli** [comment]
The error occurs inside the `CreateChild` method:

```csharp
for (int i = 0; i < firstParent.Length && childGenesIndex < firstParent.Length; i++)
{
	AddChildGene(childGenes, ref childGenesIndex, firstParent.GetGene(i));
	AddChildGene(childGenes, ref childGenesIndex, secondParent.GetGene(i));
}
```
If `childGenesIndex` is in the last position and the first `AddChildGene` increment it, the `IndexOutOfRangeException` will happen in the second `AddChildGene` call.

I added a second check to fix the problem:
```csharp
for (int i = 0; i < firstParent.Length && childGenesIndex < firstParent.Length; i++)
{
	AddChildGene(childGenes, ref childGenesIndex, firstParent.GetGene(i));

	// The childGenesIndes could be incremented by the previous AddChildGene call
	if (childGenesIndex < secondParent.Length)
		AddChildGene(childGenes, ref childGenesIndex, secondParent.GetGene(i));
}
```

A hotfix is on the way on the to the AppVeyor, in a few minutes the 2.5.2 version will be available on NuGet.

Thanks for the bug report!
