### ISSUE TITLE
Initialization of first Generation with predefined Chromosomes

### ISSUE THREAD

**Issue by WojciechOrs** [giacomelli/GeneticSharp#71]
Hi! 

I would like to initialize first Generation with my own predefined Chromosomes, not random (I have fitness function values for them). Can you please help on how to code that?

**Comment by giacomelli** [comment]
Hi, @WojciechOrs!

**Comment by giacomelli** [comment]
Hi @WojciechOrs!

**Comment by giacomelli** [comment]
Hi @WojciechOrs! 

You can use something like the `PreloadPopulation` that I proposed in this issue: 
https://github.com/giacomelli/GeneticSharp/issues/9#issuecomment-246120699
