### ISSUE TITLE
Do we have an example to use multi-threading ? 

### ISSUE THREAD

**Issue by debashis66** [giacomelli/GeneticSharp#73]
Can we modify the linear example here using multi threading - 
http://diegogiacomelli.com.br/function-optimization-with-geneticsharp/

Thanks

**Comment by giacomelli** [comment]
You can use the same code, just set the TaskExecutor as described here: https://github.com/giacomelli/GeneticSharp/wiki/multithreading

**Comment by debashis66** [comment]
Thank you for the quick reply

On a side note, I am trying to mimic large jumps (within the search space)
and small jumps in the neighborhood changing only one parameter at a time
(instead of allowing all of them to change at once). Is it possible to do
this in GA using the available crossover/ mutation operators  or do I need
to write my own implementation to achieve this ?

**Comment by debashis66** [comment]
Thank you it works
