### ISSUE TITLE
Adding as constraint to GA instead of additional objective in FuncFitness

### ISSUE THREAD

**Issue by debashis66** [giacomelli/GeneticSharp#75]
Hi Diego

How can we add constraints to GeneticAlgorithm - in my objective function defined in FuncFitness: we return 1/ (g(x) + h(x)), where g and h are defined on the chromosome values. I wanted to simplify the objective to just return 1/(g(x)) and add h(x)=0 as an additional constraint outside of the objective function

Is it possible to do this and any examples for the same ?

Thank you

**Comment by giacomelli** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
