### ISSUE TITLE
What is the best way to save the current generation data to a file so that it can be reused later.  

### ISSUE THREAD

**Issue by githubToolTester** [giacomelli/GeneticSharp#9]
I am a bit confused on the difference between resumming and starting the GA, but when I try to load in the genes that I've saved it seems as though the data is always overwritten.

Currently my gene "Value" is an int[] and I am serializing all of those to a binary file.

I am then trying to load the saved data like this:
```
    List<Gene[]> list = bf.Deserialize(inStr) as List<Gene[]>;
    var ind = 0;
    foreach(Gene[] g in list)
    {
      if(ind < this.ga.Population.CurrentGeneration.Chromosomes.Count())
      {
          this.ga.Population.CurrentGeneration.Chromosomes[ind].ReplaceGenes(0, g);
       }
    }
```

However, as soon as I call ga.resume it appears as though my data get overwritten.

Thanks for any help.

**Comment by giacomelli** [comment]
@githubToolTester it's a really good question. Could you, please, provide the code you are using to serialize them?

**Comment by githubToolTester** [comment]
Sure, 

```
            string path = "resultPopulation.bin";
            using (Stream stream = File.Open(path, FileMode.Create))
            {
                var binaryFormatter = new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();
                List<Gene[]> genes = new List<Gene[]>();
                foreach (MyChromosome nc in this.ga.Population.CurrentGeneration.Chromosomes)
                {
                    genes.Add(nc.GetGenes());
                }
                binaryFormatter.Serialize(stream, genes);
            }
```

Thanks for the help,

Alex

**Comment by githubToolTester** [comment]
I actually had a very dumb bug in my loading (missing an ind++ in the code above).  My approach works fine now, as long as I run 1 generation before I load in the saved gene data.

Thanks and sorry for the error.

**Comment by giacomelli** [comment]
Your solution is good, but there is another one: you can create a new IPopulation implementation that allow you to specified the chromosomes of the initial generation:

```csharp
public class PreloadPopulation : Population
{
	private IList<IChromosome> m_preloadChromosome;

	public PreloadPopulation(int minSize, int maxSize, IList<IChromosome> preloadChromosomes) 
		: base(minSize, maxSize, preloadChromosomes.FirstOrDefault())
	{
		m_preloadChromosome = preloadChromosomes;	
	}

	public override void CreateInitialGeneration()
	{
		Generations = new List<Generation>();
		GenerationsNumber = 0;

		foreach(var c in m_preloadChromosome) 
		{
			c.ValidateGenes();
		}

		CreateNewGeneration(m_preloadChromosome);
	}
}
```

You can see the full sample here [Issue9Sample](https://github.com/giacomelli/GeneticSharp/tree/master/src/Samples/Issue9Sample).

**Comment by githubToolTester** [comment]
Yes this is definitely better, thank you!
