### ISSUE TITLE
ToFloatingPoints() ArgumentException

### ISSUE THREAD

**Issue by Prion6** [giacomelli/GeneticSharp#93]
**Describe the bug**
ArgumentException when using ToFloatingPoints() method of the FloatingPointChromosome class

**To Reproduce**
call the function

**Expected behavior**
return an array with all the genes values

**Version:**
2.6.0

**Comment by giacomelli** [comment]
Please, can you provide a sample code where this happens?

**Comment by giacomelli** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
