### ISSUE TITLE
reinsertion control

### ISSUE THREAD

**Issue by AnakinCN** [giacomelli/GeneticSharp#96]
Hi,

Would you consider providing more specific controls on reinsertion?
1. number (or probability) of elite chromos inserted to the next generation
2. mixed reinsertion of ElitistReinsertion & FitnessBasedReinsertion 

Thank you.

**Comment by giacomelli** [comment]
Hello,

I think this kind of behavior could be easily achieved by implementing IReinsertion for specific cases. If you are willing to implement them, please propose the idea for validation in this issue, after that, if you receive a green light, you will be able to implement it and make a pull request.

Please, follow our [contributing guideline](https://github.com/giacomelli/GeneticSharp/wiki/contributing) for this.
