### ISSUE TITLE
Saving current progress

### ISSUE THREAD

**Issue by jakubwalawender** [giacomelli/GeneticSharp#97]
As my algorithm is going to last quite long I am wondering if there is any possibility to save my current progress (Population, BestChromosome, etc.)? Then having it saved, recreate an algorithm and run from this point, instead of starting with fresh Algorithm.

**Comment by giacomelli** [comment]
We've already talked about something similar to what you want in this issue  https://github.com/giacomelli/GeneticSharp/issues/9

**Comment by giacomelli** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
